school/courses/urls.py
from django.urls import path

from school.courses.views import (
    CompleteLessonView,
    CoursesListView,
    CourseView,
    LessonView,
)

urlpatterns = [
    path("courses/", CoursesListView.as_view(), name="course_list"),
    path("courses/<slug>/", CourseView.as_view(), name="course_detail"),
    path("courses/<course>/<lesson>/", LessonView.as_view(), name="lesson"),
    path("courses/<course>/<lesson>/<item>/", LessonView.as_view(), name="lesson"),
    path(
        "courses/<course>/<lesson>/<item>/complete/",
        CompleteLessonView.as_view(),
        name="complete_lesson",
    ),
]

school/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

import school.pages.views as pages

urlpatterns = [
    path("admin/", admin.site.urls),
    path("oidc/", include("mozilla_django_oidc.urls")),
    path("", pages.HomepageView.as_view()),
    path("pages/<slug>/", pages.PageView.as_view()),
    path("", include("school.courses.urls")),
    path("", include("school.problems.urls")),
    path("classrooms/", include("school.classrooms.urls")),
    path("api/import/", include("school.imports.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

school/courses/models.py
from django.db import models
from django.db.models import UniqueConstraint


class Course(models.Model):
    id: int

    name = models.CharField(max_length=64)
    order = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    image = models.ImageField(blank=True, null=True)
    short_description = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)
    recommended_courses = models.ManyToManyField("Course", blank=True)

    class Meta:
        verbose_name = "kurz"
        verbose_name_plural = "kurzy"
        ordering = ["order"]

    def __str__(self):
        return self.name


class CourseGroup(models.Model):
    id: int

    name = models.CharField(max_length=64)
    order = models.IntegerField()
    courses = models.ManyToManyField(Course, blank=True)

    class Meta:
        verbose_name = "skupina kurzov"
        verbose_name_plural = "skupiny kurzov"
        ordering = ["order"]

    def __str__(self):
        return self.name


class Lesson(models.Model):
    id: int

    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    course_id: int

    name = models.CharField(max_length=64)
    slug = models.SlugField()
    layer = models.IntegerField()
    order = models.IntegerField()

    class Meta:
        verbose_name = "lekcia"
        verbose_name_plural = "lekcie"
        constraints = [
            UniqueConstraint(fields=["course", "slug"], name="unique_course_slug"),
        ]
        ordering = ["layer", "order"]

    def __str__(self):
        return self.name

    def items(self):
        """
        Builds QuerySet for retrieving all lesson items with related data
        :return: QuerySet
        """
        return self.lessonitem_set.order_by("order").select_related(
            "lesson_material", "problem"
        )


class LessonMaterial(models.Model):
    id: int

    name = models.CharField(max_length=64)
    material_id = models.SlugField(unique=True)
    content = models.TextField(blank=True)

    class Meta:
        verbose_name = "učebný text"
        verbose_name_plural = "učebné texty"

    def __str__(self):
        return self.name


class LessonItem(models.Model):
    id: int

    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    lesson_id: int

    order = models.IntegerField()
    slug = models.SlugField(max_length=64)

    lesson_material = models.ForeignKey(
        LessonMaterial, on_delete=models.CASCADE, blank=True, null=True
    )
    problem = models.ForeignKey(
        "problems.Problem", on_delete=models.CASCADE, blank=True, null=True
    )

    class Meta:
        verbose_name = "časť lekcie"
        verbose_name_plural = "časti lekcie"
        constraints = [
            UniqueConstraint(fields=["lesson", "slug"], name="unique_lesson_slug"),
        ]
        ordering = ["order"]

    def __str__(self):
        return self.name

    @property
    def name(self):
        if self.lesson_material:
            return self.lesson_material.name
        if self.problem:
            return self.problem.name
        return "???"

school/problems/models.py
import secrets
from os import path

from django.conf import settings
from django.db import models
from django.urls import reverse
from judge_client.types import SubmitStatus, TestingStatus, Verdict

from school.utils import get_extension


def submit_file_filepath(instance: "Submit", filename):
    _, ext = path.splitext(filename)
    rnd_str = secrets.token_hex(16)
    return f"submits/{instance.problem_id}/{instance.user_id}_{rnd_str}{ext}"


class Tag(models.Model):
    id: int

    name = models.CharField(verbose_name="názov", max_length=256)

    class Meta:
        verbose_name = "tag"
        verbose_name_plural = "tagy"

    def __str__(self):
        return self.name


class Problem(models.Model):
    class ProblemDifficulty(models.TextChoices):
        EASY = "easy", "easy"
        MEDIUM = "medium", "medium"
        HARD = "hard", "hard"
        UNKNOWN = "unknown", "unknown"

    id: int

    name = models.CharField(verbose_name="názov", max_length=64)
    slug = models.SlugField(
        verbose_name="slug",
        max_length=64,
        unique=True,
    )
    content = models.TextField(verbose_name="zadanie", blank=True)
    difficulty = models.CharField(
        verbose_name="obtiažnosť",
        choices=ProblemDifficulty.choices,
        default=ProblemDifficulty.UNKNOWN,
    )
    judge_namespace = models.CharField(
        verbose_name="namespace v ktorom je úloha v Judgi",
        max_length=128,
        default="",
        blank=True,
    )
    judge_task = models.CharField(verbose_name="názov úlohy pre Judge", max_length=128)
    tags = models.ManyToManyField(Tag)

    class Meta:
        verbose_name = "úloha"
        verbose_name_plural = "úlohy"

        constraints = [
            models.UniqueConstraint(
                "judge_task",
                "judge_namespace",
                name="problem__judge_task_judge_namespace",
            )
        ]

    def __str__(self):
        return self.name


class Submit(models.Model):
    class JudgeTestingStatus(models.IntegerChoices):
        QUEUED = 0, "queued"
        FINISHED = 1, "finished"
        FAILED = 2, "failed"

    id: int

    problem = models.ForeignKey(Problem, on_delete=models.CASCADE, verbose_name="úloha")
    problem_id: int
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="používateľ"
    )
    user_id: int
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="čas", db_index=True
    )

    program = models.FileField(
        verbose_name="odovzdaný program",
        upload_to=submit_file_filepath,
        max_length=255,
    )

    status = models.SmallIntegerField(
        choices=JudgeTestingStatus.choices,
        verbose_name="status submitu na Judgi",
        default=JudgeTestingStatus.QUEUED,
    )
    testing_status = models.CharField(
        max_length=32, blank=True, default="", verbose_name="status testovania na Judgi"
    )

    result = models.CharField(blank=True, max_length=16, verbose_name="verdikt")
    public_id = models.CharField(
        max_length=255,
        unique=True,
        verbose_name="public ID submitu",
        null=True,
        default=None,
        blank=True,
    )
    protocol_key = models.CharField(max_length=255, blank=True)

    lesson_item = models.ForeignKey(
        "courses.LessonItem",
        blank=True,
        null=True,
        verbose_name="časť lekcie",
        on_delete=models.SET_NULL,
    )
    lesson_item_id: int

    class Meta:
        verbose_name = "submit"
        verbose_name_plural = "submity"
        ordering = ("-created_at",)

    def __str__(self):
        return f"Submit {self.id}"

    def get_absolute_url(self):
        return reverse(
            "submit_detail",
            kwargs={"problem": self.problem.slug, "submit": self.id},
        )

    @property
    def language(self) -> str:
        return get_extension(self.program.path)

    @property
    def status_pretty(self) -> str:
        if self.result:
            return self.result_pretty

        if self.status == self.JudgeTestingStatus.QUEUED and self.testing_status:
            return TestingStatus(self.testing_status).get_human_name("sk")

        return SubmitStatus(self.status).get_human_name("sk")

    @property
    def result_pretty(self) -> str:
        return Verdict(self.result).get_human_name("sk")

    @property
    def result_color(self) -> str:
        if not self.result:
            return "gray"
        return Verdict(self.result).color

school/courses/views.py
from itertools import groupby

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView

from school.courses.models import Course, CourseGroup, Lesson, LessonItem
from school.problems.models import Submit
from school.trackers.helpers import (
    get_course_groups_with_trackers,
    get_items_with_trackers,
    get_lessons_with_trackers,
)
from school.trackers.models import TrackerState
from school.trackers.utils import get_or_create_trackers, mark_completed


class CoursesListView(ListView):
    template_name = "courses/list.html"

    def get_queryset(self):
        return CourseGroup.objects.order_by("order").prefetch_related("courses").all()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["groups"] = get_course_groups_with_trackers(
            self.object_list, self.request.user
        )
        return ctx


class CourseView(DetailView):
    template_name = "courses/detail.html"
    model = Course

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        lessons = get_lessons_with_trackers(
            Lesson.objects.filter(course=self.object).order_by("layer", "order").all(),
            self.request.user,
        )

        layers = []
        for _, layer_lessons in groupby(lessons, key=lambda x: x.lesson.layer):
            layers.append(list(layer_lessons))

        ctx["layers"] = layers
        ctx["done"] = all(
            all(
                lesson.tracker is not None
                and lesson.tracker.state == TrackerState.COMPLETE
                for lesson in layer
            )
            for layer in layers
        )
        return ctx


class LessonView(TemplateView):
    template_name = "courses/lesson.html"

    def dispatch(self, request, *args, **kwargs):
        self.lesson = get_object_or_404(
            Lesson,
            slug=kwargs["lesson"],
            course__slug=kwargs["course"],
        )

        if "item" in kwargs:
            self.item: LessonItem = get_object_or_404(
                self.lesson.lessonitem_set, slug=kwargs["item"]
            )
        else:
            first_item = self.lesson.lessonitem_set.order_by("order").first()
            if not first_item:
                raise Http404()

            return redirect(
                "lesson",
                course=kwargs["course"],
                lesson=self.lesson.slug,
                item=first_item.slug,
            )

        return super(LessonView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        items = self.lesson.items().all()
        next_item = next(iter(filter(lambda x: x.order > self.item.order, items)), None)
        previous_item = next(
            iter(filter(lambda x: x.order < self.item.order, reversed(items))), None
        )

        submits = None
        if self.item.problem and self.request.user.is_authenticated:
            submits = Submit.objects.filter(
                problem=self.item.problem,
                user=self.request.user,
                lesson_item=self.item,
            )

        # Tracking:
        tracker, item_tracker = None, None
        if self.request.user.is_authenticated:
            item_tracker, tracker, _ = get_or_create_trackers(
                self.item, self.request.user
            )

        ctx.update(
            {
                "lesson": self.lesson,
                "tracker": tracker,
                "item_tracker": item_tracker,
                "item": self.item,
                "items": get_items_with_trackers(items, self.request.user),
                "submits": submits,
                "previous_item": previous_item,
                "next_item": next_item,
            }
        )
        return ctx


class CompleteLessonView(View, LoginRequiredMixin):
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        lesson = get_object_or_404(
            Lesson,
            slug=kwargs["lesson"],
            course__slug=kwargs["course"],
        )

        item: LessonItem = get_object_or_404(lesson.lessonitem_set, slug=kwargs["item"])

        if self.request.user.is_authenticated:
            if item.lesson_material:
                _, tracker, _ = mark_completed(item, self.request.user)

        return redirect(
            "lesson",
            course=kwargs["course"],
            lesson=lesson.slug,
            item=item.slug,
        )

school/courses/templates/courses/detail.html
{% extends 'common/base.html' %}
{% load markdownify %}

{% block title %}{{ course.name }} {{ block.super }}{% endblock %}

{% block body %}
    <div class="container mx-auto flex flex-col lg:flex-row py-10 lg:py-20 px-6 lg:items-center gap-2 lg:gap-6">
        {% if course.image %}
        <img src="{{ course.image.url }}" class="w-20 h-20 border border-gray-600 rounded-md shadow-inner">
        {% endif %}

        <div>
            <a href="{% url "course_list" %}" class="items-center inline-flex text-blue-300 gap-1 mb-4 hover:text-blue-400 hover:underline"><i data-feather="arrow-left" class="w-4 h-4"></i> Späť na zoznam kurzov</a>
            
            <h1 class="tracking-tight text-3xl text-white font-bold lg:text-5xl">{{ course.name|markdownify }}</h1>
            <div class="mt-2 lg:mt-4 prose prose-invert max-w-none">
                {{ course.description|markdownify }}
            </div>
        </div>
    </div>

    {% if done %}
        <div class="container mx-auto mb-10 lg:mb-20 p-8 lg:items-center gap-2 lg:gap-6 text-white bg-green-800 border border-green-600 rounded-md">
            <p class="font-bold">
                🎉 Gratulujeme, úspešne si dokončil/a tento kurz!
            </p>

            {% with course.recommended_courses.all as next %}
            {% if next|length %}
                <p class="mt-2">
                    Asi sa pýtaš, čo ďalej, a my to vieme. Môžeš pokračovať týmito kurzami:
                </p>
                <ul class="list-inside list-disc mt-2 ml-4">
                {% for course in next %}
                    <li><a href="{% url 'course_detail' course.slug %}" class="text-blue-300 hover:text-blue-400 underline">{{ course }}</a></li>
                {% endfor %}
                </ul>
            {% endif %}
            {% endwith %}
        </div>
    {% endif %}

    <div class="container mx-auto px-6">
        <div class="flex flex-col md:flex-row text-white items-center overflow-x-auto gap-4">
            {% for layer in layers %}
                <div class="gap-2 flex flex-col">
                    {% for lt in layer %}
                    <a href="{% url 'lesson' course.slug lt.lesson.slug %}" class="px-3 py-2 border rounded-md flex items-center gap-2 {% if not lt.tracker %}border-gray-700 bg-gray-800{% elif lt.tracker.state == lt.tracker.state.STARTED %}border-blue-600 bg-blue-800{% elif lt.tracker.state == lt.tracker.state.COMPLETE %}border-green-600 bg-green-800{% elif lt.tracker.state == lt.tracker.state.FASTFORWARD %}border-cyan-600 bg-cyan-800{% endif %}">
{#                            <div data-tippy-content="Checkpoint">#}
{#                                <i class="w-4 h-4" data-feather="flag"></i>#}
{#                            </div>#}

                        {{ lt.lesson.name|markdownify }}

                        {% if lt.tracker %}
                            <div class="ml-auto shrink-0">
                                {% if lt.tracker.state == lt.tracker.state.STARTED %}
                                <span class="text-xs text-blue-300">{{ lt.tracker.completed }}/{{ lt.tracker.total }}</span>
                                {% elif lt.tracker.state == lt.tracker.state.COMPLETE %}
                                <i class="w-4 h-4 text-green-400" data-feather="check"></i>
                                {% elif lt.tracker.state == lt.tracker.state.FASTFORWARD %}
                                <div data-tippy-content="Túto lekciu si preskočil/-a">
                                    <i class="w-4 h-4 text-cyan-500" data-feather="fast-forward"></i>
                                </div>
                                {% endif %}
                            </div>
                        {% endif %}
                    </a>
                    {% endfor %}
                </div>

                {% if not forloop.last %}
                <i data-feather="chevron-right" class="text-gray-500 hidden md:block"></i>
                <i data-feather="chevron-down" class="text-gray-500 md:hidden"></i>
                {% endif %}
            {% endfor %}
        </div>
    </div>

{% endblock %}

school/courses/templates/courses/lesson.html
{% extends 'common/base.html' %}
{% load percent %}
{% load submits %}
{% load markdownify %}

{% block title %}{{ item.name }} {{ block.super }}{% endblock %}

{% block body_class %}min-h-screen flex flex-col{% endblock %}

{% block body %}

    <div class="flex grow flex-col lg:flex-row">
        <aside class="bg-gray-800 lg:border-r border-b lg:border-b-0 border-gray-600 lg:w-80 flex flex-col p-6 text-gray-400 ">
            <div class="flex flex-col lg:flex-row lg:items-center gap-4">
                {% if lesson.course.image %}
                <img src="{{ lesson.course.image.url }}" class="w-16 h-16 border border-gray-600 rounded-md shadow-inner">
                {% endif %}

                <div class="text-white w-full">
                    <a href="{% url 'course_detail' lesson.course.slug %}" class="font-medium text-gray-300 text-base flex w-full items-center">{{ lesson.course.name|markdownify }} <span class="ml-auto text-xs">Späť na kurz</span></a>
                    <div class="font-bold text-xl lg:text-2xl">{{ lesson.name|markdownify }}</div>
                </div>
            </div>

            {% if user.is_authenticated %}
                <div class="rounded-md bg-gray-700 w-full h-2 mt-2 lg:mt-4">
                    <div class="rounded-md {% if tracker.state == tracker.state.COMPLETE %}bg-green-500{% else %}bg-blue-600{% endif %} h-2" style="width: {% percent tracker.completed tracker.total %}%"></div>
                </div>
            {% endif %}

            <hr class="my-4 lg:my-6 border-gray-600">

            <nav class="flex">
                <ul class="flex flex-col gap-1 lg:gap-2 lg:text-base text-sm w-full">
                    {% for it in items %}
                    <li>
                        <a href="{% url 'lesson' lesson.course.slug lesson.slug it.item.slug %}" class="flex gap-1.5 items-center {% if item == it.item %}text-white font-bold{% endif %}">
                            <i data-feather="{% if it.item.problem %}code{% else %}file-text{% endif %}" class="w-4 h-4 shrink-0"></i>

                            {{ it.item.name|markdownify }}

                            {% if it.tracker and it.tracker.state == it.tracker.state.COMPLETE %}
                                <i data-feather="check" class="ml-auto w-4 h-4 text-green-500 shrink-0"></i>
                            {% endif %}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </nav>
        </aside>

        <div class="grow px-6 py-8">
            <div class="mx-auto prose prose-invert">
                {% if item.lesson_material %}
                    {% if user.is_authenticated %}
                        <div class="text-right">
                            <form action="{% url 'complete_lesson' course lesson.slug item.slug %}" method="post">
                                {% csrf_token %}
                                <label><input type="checkbox" onclick="submit()" {% if item_tracker.state == tracker.state.COMPLETE %}checked{% endif %}> Označiť ako dokončené</label>
                            </form>
                        </div>
                    {% endif %}

                    {{ item.lesson_material.content|markdownify }}

                    {% if user.is_authenticated %}
                        <div class="text-right">
                            <form action="{% url 'complete_lesson' course lesson.slug item.slug %}" method="post">
                                {% csrf_token %}
                                <label><input type="checkbox" onclick="submit()" {% if item_tracker.state == tracker.state.COMPLETE %}checked{% endif %}> Označiť ako dokončené</label>
                            </form>
                        </div>
                    {% endif %}
                {% elif item.problem %}
                    <div class="mb-5">
                        <b>Tagy: </b>
                        {% for tag in item.problem.tags.all %}
                            <span class="bg-blue-900 rounded-md p-2 m-1">
                                {{ tag }}
                            </span>
                        {% endfor %}
                    </div>
                    <div class="mb-5">
                        {% if item.problem.difficulty == item.problem.ProblemDifficulty.EASY %}
                            <b>Obtiažnosť:</b>
                            <span class="bg-green-900 rounded-md p-2 m-1" data-tippy-content="Úloha by mala byť zvládnuteľná bez väčších problémov.">
                                easy
                            </span>
                        {% elif item.problem.difficulty == item.problem.ProblemDifficulty.MEDIUM %}
                            <b>Obtiažnosť:</b>
                            <span class="bg-orange-900 rounded-md p-2 m-1" data-tippy-content="Úloha nemusí mať úplne priamočiare riešenie.">
                                medium
                            </span>
                        {% elif item.problem.difficulty == item.problem.ProblemDifficulty.HARD %}
                            <b>Obtiažnosť:</b>
                            <span class="bg-red-900 rounded-md p-2 m-1" data-tippy-content="Úloha vyžaduje pokročilé vedomosti z iných kurzov.">
                                hard
                            </span>
                        {% endif %}
                    </div>
                    {{ item.problem.content|markdownify }}
                {% endif %}
            </div>

            {% if item.problem %}
                <div class="max-w-prose mx-auto my-6">
                    {% if user.is_authenticated %}

                        <h2 class="text-white font-bold text-2xl mb-4">Odovzdávanie programu</h2>
                        {% submit_form item.problem lesson_item_id=item.id %}

                        {% if user.is_staff %}
                            <a href="{% url 'admin:problems_submit_changelist' %}?problem__slug={{ item.problem.slug }}" class="btn mt-10">
                                <i data-feather="list" class="h-4"></i>
                                Zobraz všetky submity
                            </a>
                        {% endif %}

                        {% if submits %}
                        <h2 class="text-white font-bold text-2xl mt-10 mb-4">Posledné submity</h2>
                        {% submit_list submits lesson_item_id=item.id %}
                        {% endif %}
                    {% else %}
                        <div class="w-full rounded-md px-4 py-3 bg-red-900 border border-red-600 text-white">
                            Ak chceš riešiť túto úlohu, musíš sa najprv <a href="{% url 'oidc_authentication_init' %}" class="underline hover:text-red-300">prihlásiť</a>.
                        </div>
                    {% endif %}
                </div>
            {% endif %}

            <div class="max-w-prose mx-auto flex flex-wrap gap-2 my-10">
                {% if previous_item %}
                    <a href="{% url 'lesson' lesson.course.slug lesson.slug previous_item.slug %}" class="btn">
                        <i data-feather="arrow-left" class="h-4"></i>
                        Späť
                    </a>
                {% endif %}
                {% if next_item %}
                    <a href="{% url 'lesson' lesson.course.slug lesson.slug next_item.slug %}" class="btn ml-auto">
                        Ďalej
                        <i data-feather="arrow-right" class="h-4"></i>
                    </a>
                {% else %}
                    <a href="{% url 'course_detail' lesson.course.slug %}" class="btn-cyan ml-auto">
                        Naspäť na kurz
                        <i data-feather="corner-right-up" class="h-4"></i>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

school/courses/templates/courses/list.html
{% extends 'common/base.html' %}
{% load percent %}

{% block title %}Zoznam kurzov {{ block.super }}{% endblock %}

{% block body %}
    <div class="container mx-auto flex flex-col lg:flex-row py-10 lg:py-16 px-6 lg:items-center">
        <div class="lg:max-w-lg">
            <h1 class="tracking-tight text-3xl text-white font-bold lg:text-5xl">Zoznam kurzov</h1>
            <p class="mt-6 text-gray-400">
                Na tejto stránke sa nachádza zoznam kurzov.
                Neskoršie kurzy nadväzujú na poznatky z predchádzajúcich,
                preto ich odporúčame absolvovať po poradí.
            </p>
        </div>
    </div>



    {% for t in groups %}
    <div class="container mx-auto px-6 py-6">
        <h1 class="tracking-tight text-xl text-white font-bold lg:text-3xl mb-6">{{ t.group.name }}</h1>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-1">
        {% for ct in t.courses %}
            <a href="{% url 'course_detail' ct.course.slug %}" class="text-gray-400 p-6 flex flex-col text-center hover:bg-gray-800 cursor-pointer lg:items-center gap-4 rounded-md">
                {% if ct.course.image %}
                <img src="{{ ct.course.image.url }}" class="w-20 h-20 border border-gray-600 rounded-md shadow-inner">
                {% endif %}

                <div class="w-full">
                    <h2 class="text-white font-bold text-xl lg:text-2xl">{{ ct.course.name }}</h2>
                    <p class="mt-2">
                        {{ ct.course.short_description }}
                    </p>

                    {% if ct.tracker %}
                    <div class="rounded-md bg-gray-700 w-full h-2 mt-4">
                        <div class="rounded-md {% if ct.tracker.state == ct.tracker.state.COMPLETE %}bg-green-500{% else %}bg-blue-600{% endif %} h-2" style="width: {% percent ct.tracker.completed ct.tracker.total %}%"></div>
                    </div>
                    {% endif %}
                </div>
            </a>
        {% endfor %}
        </div>
    </div>
    {% endfor %}



{% endblock %}